dist: bionic
language: ruby
addons:
  postgresql: "9.6"
rvm:
  - 2.7.1
env:
  global:
    RAILS_ENV: test
    RACK_TIMEOUT_SERVICE_TIMEOUT: 15
    SPACED_THREADS: 5
    SPACED_PUBLIC_URL: http://localhost:3000
    SPACED_SERVER_PORT: 3000
    # SPACED_DB_HOST:
    # SPACED_DB_USER:
    # SPACED_DB_PASS:
    SPACED_DB_NAME: postgres
    SECRET_KEY_BASE: secret
    SPACED_REPLY_TO_EMAIL: noreply@example.com
script:
  - bundle exec rake test

