dist: bionic
language: ruby
addons:
  postgresql: "9.6"
rvm: 2.7.1
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: "1"
    RACK_TIMEOUT_SERVICE_TIMEOUT: "15"
    RAILS_ENV: test
    SECRET_KEY_BASE: secret
    SPACED_DB_NAME: spaced_test
    SPACED_DB_USER: postgres
    SPACED_PUBLIC_URL: http://localhost:3000
    SPACED_REPLY_TO_EMAIL: noreply@example.com
    SPACED_SERVER_PORT: "3000"
    SPACED_THREADS: "5"
install:
  - nvm install 12.16.3
  - npm install --no-save -g yarn
  - bin/setup
script:
  - bundle exec rake

