default: &default
  encoding: unicode
  adapter: <%= ENV.fetch("SPACED_DB_ADAPTER", "postgresql") %>
  host: <%= ENV.fetch("SPACED_DB_HOST", "127.0.0.1") %>
  username: <%= ENV["SPACED_DB_USER"] %>
  password: <%= ENV["SPACED_DB_PASS"] %>
  database: <%= ENV["SPACED_DB_NAME"] %>
  pool: <%= ENV.fetch("SPACED_THREADS", "5") %>

development:
  <<: *default
  database: <%= ENV.fetch("SPACED_DB_NAME", "spaced_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("SPACED_DB_NAME", "spaced_test") %>

production:
  <<: *default

