default: &default
  encoding: unicode
  adapter: <%= ENV.fetch("SPACED_DB_ADAPTER", "postgresql") %>
  host: <%= ENV.fetch("SPACED_DB_HOST", "127.0.0.1") %>
  username: <%= ENV["SPACED_DB_USER"] %>
  password: <%= ENV["SPACED_DB_PASS"] %>
  database: <%= ENV["SPACED_DB_NAME"] %>
  pool: <%= ENV.fetch("SPACED_THREADS", "5") %>
  # NOTE: set proper timeouts
  connect_timeout: 2 # seconds
  checkout_timeout: 10 # seconds
  variables:
    statement_timeout: <%= ENV.fetch("SPACED_DB_STATEMENT_TIMEOUT", "1s") %>

development:
  <<: *default
  database: <%= ENV.fetch("SPACED_DB_NAME", "spaced_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("SPACED_DB_NAME", "spaced_test") %>

production:
  <<: *default

